# Generated by Django 4.0 on 2022-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='BloodPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='BloodSugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='LastAvgHeartRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='LastAvgTemp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='Height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='Weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
