# Generated by Django 4.0 on 2022-03-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0003_testingapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingapi',
            name='string',
            field=models.CharField(default='', max_length=200),
        ),
    ]
