# Generated by Django 4.0 on 2022-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0005_dailydata_lastavgoxygen_secondlydata_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='EmailID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
