# Generated by Django 4.0 on 2022-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0007_patientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patients',
            name='BloodType',
            field=models.CharField(default='A+', max_length=3),
        ),
    ]
